env:
  browser: true
  es2021: true
extends:
  #- google
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  semi: error
  max-len:
    - error
    - 120
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"

overrides:
  - files:
      - "*.ts"
      - "*.tsx"
