name: "Terraform checks"
on:
  push:
    branches:
      - main
  pull_request:
    paths: ["**/*.tf", "**/*.hcl", ".github/workflows/terraform.yml"]

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION: eu-west-1
jobs:
  verify_module:
    name: Verify module
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.5.3
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: "Fake zip files" # Validate will fail if it cannot find the zip files
        run: |
          touch lambdas/functions/webhook/webhook.zip
          touch lambdas/functions/control-plane/runners.zip
          touch lambdas/functions/gh-agent-syncer/runner-binaries-syncer.zip
          touch lambdas/functions/ami-housekeeper/ami-housekeeper.zip
      - name: terraform init
        working-directory: emqx
        run: terraform init -get -backend=false -input=false
      - name: check terraform formatting
        working-directory: emqx
        run: terraform fmt -recursive -check=true -write=false
        continue-on-error: true
      - name: validate terraform
        working-directory: emqx
        run: terraform validate
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run TFLint
        working-directory: emqx
        run: tflint -f compact
